# This workflow will publish RC releases to maven central and create the tag on git

name: Java CD for Release with Maven

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag-rc-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Check if branch is release branch
        id: is_release_branch
        run: |
          echo "Checking if branch is a release branch"
          if [[ "${{ github.ref }}" =~ ^refs/heads/release/.*$ ]]; then
            echo "This is a release branch"
            echo "is_release_branch=true" >> $GITHUB_ENV
          else
            echo "This is not a release branch"
            echo "is_release_branch=false" >> $GITHUB_ENV
          fi

      - name: Set up Git
        if: env.is_release_branch == 'true'
        run: |
          echo "Setting up Git"
          git --version
          git config user.name "GitHub Action Bot"
          git config user.email "<>"
      - name: Get Release tag
        if: env.is_release_branch == 'true'
        id: latest_rc_tag
        run: |
          echo "Getting the latest RC tag"
          current_release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///')
          echo "current_release_version=${current_release_version}"
          echo "release_tag=${current_release_version}" >> $GITHUB_ENV

      - name: Deploy to Maven Central
        if: env.is_release_branch == 'true' && env.release_tag != ''
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          echo "Deploying artifact with Release tag: ${{ env.release_tag }}"
          mvn --batch-mode -DskipTests -Denv=cd-maven -Drevision=${{ env.release_tag }} clean deploy

      - name: Create new Release tag
        if: env.is_release_branch == 'true' && env.release_tag != ''
        run: |
          echo "Creating new Release tag: ${{ env.release_tag }}"
          git tag ${{ env.release_tag }}

      - name: Push Release tag to GitHub
        if: env.is_release_branch == 'true' && env.release_tag != ''
        run: |
          echo "Pushing Release tag to GitHub: ${{ env.release_tag }}"
          git push origin ${{ env.release_tag }}
