# This workflow will publish RC releases to maven central and create the tag on git

name: Java CD for RC with Maven

on:
  workflow_dispatch:

jobs:
  tag-rc-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if branch is release branch
        id: is_release_branch
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/heads/release/.*$ ]]; then
            echo "This is a release branch"
            echo "::set-output name=is_release_branch::true"
          else
            echo "This is not a release branch"
            echo "::set-output name=is_release_branch::false"
          fi

      - name: Set up Git
        if: steps.is_release_branch.outputs.is_release_branch == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get latest RC tag
        if: steps.is_release_branch.outputs.is_release_branch == 'true'
        id: latest_rc_tag
        run: |
          current_release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/release\///')
          latest_rc_tag=$(git describe --tags --match "${current_release_version}-RC*" --abbrev=0 2>/dev/null || echo "")
          if [ -z "$latest_rc_tag" ]; then
            echo "No existing RC tags found"
            latest_rc_tag="${current_release_version}-RC1"
          else
            latest_rc_number=$(echo "$latest_rc_tag" | grep -o '[0-9]*$')
            next_rc_number=$((latest_rc_number + 1))
            echo "::set-output name=next_rc_tag::${current_release_version}-RC$next_rc_number"
          fi

      - name: Create new RC tag
        if: steps.is_release_branch.outputs.is_release_branch == 'true' && steps.latest_rc_tag.outputs.next_rc_tag != ''
        run: |
          git tag ${{ steps.latest_rc_tag.outputs.next_rc_tag }}
          echo "Tagged code with RC tag: ${{ steps.latest_rc_tag.outputs.next_rc_tag }}"

      - name: Push RC tag to GitHub
        if: steps.is_release_branch.outputs.is_release_branch == 'true' && steps.latest_rc_tag.outputs.next_rc_tag != ''
        run: |
          git push origin ${{ steps.latest_rc_tag.outputs.next_rc_tag }}
          echo "Pushed RC tag to GitHub: ${{ steps.latest_rc_tag.outputs.next_rc_tag }}"

      - name: Deploy to Maven Central
        if: steps.is_release_branch.outputs.is_release_branch == 'true' && steps.latest_rc_tag.outputs.next_rc_tag != ''
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn clean deploy -Drevision=${{ steps.latest_rc_tag.outputs.next_rc_tag }}
          echo "Deployed artifact with RC tag: ${{ steps.latest_rc_tag.outputs.next_rc_tag }}"
